const actionsList = {
  ui: {
    SET_TIMELINES_FILTER: 'SET_TIMELINES_FILTER',
    OPEN_MODAL: 'OPEN_MODAL',
  },
  timeline: {
    START_CREATE_TIMELINE: 'START_CREATE_TIMELINE',
    SUCCESS_CREATE_TIMELINE: 'SUCCESS_CREATE_TIMELINE',
    ERROR_CREATE_TIMELINE: 'ERROR_CREATE_TIMELINE',

    START_EDIT_TIMELINE: 'START_EDIT_TIMELINE',
    SUCCESS_EDIT_TIMELINE: 'SUCCESS_EDIT_TIMELINE',
    ERROR_EDIT_TIMELINE: 'ERROR_EDIT_TIMELINE',

    START_DELETE_TIMELINE: 'START_DELETE_TIMELINE',
    SUCCESS_DELETE_TIMELINE: 'SUCCESS_DELETE_TIMELINE',
    ERROR_DELETE_TIMELINE: 'ERROR_DELETE_TIMELINE',

    START_FETCH_EVENTS: 'START_FETCH_EVENTS',
    SUCCESS_FETCH_EVENTS: 'SUCCESS_FETCH_EVENTS',
    ERROR_FETCH_EVENTS: 'ERROR_FETCH_EVENTS',
  },
  timelines: {
    START_FETCH_TIMELINES: 'START_FETCH_TIMELINES',
    SUCCESS_FETCH_TIMELINES: 'SUCCESS_FETCH_TIMELINES',
    ERROR_FETCH_TIMELINES: 'ERROR_FETCH_TIMELINES',
  },
  event: {
    START_CREATE_EVENT: 'START_CREATE_EVENT',
    SUCCESS_CREATE_EVENT: 'SUCCESS_CREATE_EVENT',
    ERROR_CREATE_EVENT: 'ERROR_CREATE_EVENT',

    START_EDIT_EVENT_TITLE: 'START_EDIT_EVENT_TITLE',
    SUCCESS_EDIT_EVENT_TITLE: 'SUCCESS_EDIT_EVENT_TITLE',
    ERROR_EDIT_EVENT_TITLE: 'ERROR_EDIT_EVENT_TITLE',

    START_EDIT_EVENT_DESCRIPTION: 'START_EDIT_EVENT_DESCRIPTION',
    SUCCESS_EDIT_EVENT_DESCRIPTION: 'SUCCESS_EDIT_EVENT_DESCRIPTION',
    ERROR_EDIT_EVENT_DESCRIPTION: 'ERROR_EDIT_EVENT_DESCRIPTION',

    START_DELETE_EVENT: 'START_DELETE_EVENT',
    SUCCESS_DELETE_EVENT: 'SUCCESS_DELETE_EVENT',
    ERROR_DELETE_EVENT: 'ERROR_DELETE_EVENT',

    START_LINK_EVENT: 'START_LINK_EVENT',
    SUCCESS_LINK_EVENT: 'SUCCESS_LINK_EVENT',
    ERROR_LINK_EVENT: 'ERROR_LINK_EVENT',

    START_UNLINK_EVENT: 'START_UNLINK_EVENT',
    SUCCESS_UNLINK_EVENT: 'SUCCESS_UNLINK_EVENT',
    ERROR_UNLINK_EVENT: 'ERROR_UNLINK_EVENT',

    START_GET_LINKED_EVENTS: 'START_GET_LINKED_EVENTS',
    SUCCESS_GET_LINKED_EVENTS: 'SUCCESS_GET_LINKED_EVENTS',
    ERROR_GET_LINKED_EVENTS: 'ERROR_GET_LINKED_EVENTS'
  },
}

export default actionsList
